### PR TITLE
Fix #46: Remove unused import

### LINKED ISSUE #46: paper-ripple
I see paper-ripple.html is imported, but I don't see where it is used.

https://github.com/PolymerElements/paper-fab/blob/master/paper-fab.html#L16

In the 0.5 version, I was able to disable the ripple by :

```
      #backbutton::shadow paper-ripple {
        display: none;
      }
```

but I don't see how to do this with the new version. Any pointers?

### PR DESCRIPTION
**Pull request by abdonrd**
Fix #46: Remove unused import

### CODE REVIEW

**Comment by keanulee** [comment]
Actually, `paper-ripple` is used - it's dynamically created by `PaperRippleBehavior`

**Comment by abdonrd** [comment]
@keanulee Yes, but the `paper-button-behavior.html` imports the `paper-ripple-behavior.html` that imports the `paper-ripple.html`. :)

**Comment by keanulee** [comment]
Ref PolymerElements/paper-button#82

**Comment by abdonrd** [comment]
@keanulee now we can open and merge this? :smiley:

**Comment by keanulee** [comment]
I can't reopen this PR because GitHub won't let me ("The issue_46 branch was force-pushed or recreated). Feel free to submit a new PR.

**Pull request closed without merging**
